[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
solc = "0.8.23"

[profile.forked]
fork_block_number = 18814000
fork_url = "mainnet"

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = "sepolia"}